name: m3builderai
description: "A new Flutter project using Material 3."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  flutter_colorpicker: ^1.0.3
  file_picker: ^5.3.1
  path_provider: ^2.1.0
  url_launcher: ^6.1.12
  flex_color_scheme: ^7.3.1
  flutter_svg: ^2.0.7
  google_fonts: ^5.1.0  # Ajout de google_fonts pour utiliser Montserrat sans fichiers TTF

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Vous devez créer un dossier assets à la racine du projet
  # et y copier les fichiers depuis lib/views/screens/oroneo/
  assets:
    - assets/oroneo/logos/Logodark.svg
    - assets/oroneo/logos/Logolight.svg
    - assets/oroneo/logos/Odark.svg
    - assets/oroneo/logos/Ogrey.svg
    - assets/oroneo/logos/Olight.svg
    - assets/oroneo/carousel/
    - assets/oroneo/icons/
  
  # Nous utiliserons google_fonts au lieu des fichiers TTF locaux
  # fonts:
  #   - family: Montserrat
  #     fonts:
  #       - asset: assets/fonts/Montserrat-Regular.ttf
  #       - asset: assets/fonts/Montserrat-Italic.ttf
  #         style: italic
  #       - asset: assets/fonts/Montserrat-Bold.ttf
  #         weight: 700
  #       - asset: assets/fonts/Montserrat-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/Montserrat-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Montserrat-Light.ttf
  #         weight: 300