name: m3builderai
description: "A new Flutter project using Material 3."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  flutter_colorpicker: ^1.0.3
  file_picker: ^5.3.1
  path_provider: ^2.1.1
  url_launcher: ^6.1.12
  flex_color_scheme: ^7.3.1
  flutter_svg: ^2.0.7
  google_fonts: ^5.1.0  # Ajout de google_fonts pour utiliser Montserrat sans fichiers TTF
  http: ^1.1.0
  permission_handler: ^10.4.3
  flutter_carousel_widget: ^2.1.2  # Essayez une version plus récente si disponible
  font_awesome_flutter: ^10.8.0
  fl_chart: ^0.65.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  # Supprimer la partie fonts: MaterialIcons
  assets:
    - assets/oroneo/
    - assets/oroneo/logos/
    - assets/oroneo/logos/Logodark.svg
    - assets/oroneo/logos/Logolight.svg
    - assets/oroneo/logos/Odark.svg
    - assets/oroneo/logos/Ogrey.svg
    - assets/oroneo/logos/Olight.svg
    - assets/oroneo/images/
    - assets/oroneo/images/claire.png
    - assets/oroneo/icons/
    - assets/oroneo/icons/AppleLogo.svg
    - assets/oroneo/icons/appleRainbow.svg
    - assets/oroneo/icons/GoogleGlogo.svg
    - assets/oroneo/fonts/
    - assets/oroneo/carousel/
  
  # Nous utiliserons google_fonts au lieu des fichiers TTF locaux
  # fonts:
  #   - family: Montserrat
  #     fonts:
  #       - asset: assets/fonts/Montserrat-Regular.ttf
  #       - asset: assets/fonts/Montserrat-Italic.ttf
  #         style: italic
  #       - asset: assets/fonts/Montserrat-Bold.ttf
  #         weight: 700
  #       - asset: assets/fonts/Montserrat-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/Montserrat-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Montserrat-Light.ttf
  #         weight: 300